"""Animora AI/ML visualization module for math surfaces, classic ML, deep learning, and NLP."""

from __future__ import annotations

from animora.ml.base import MLComponent, MLTrace, MLTraceStep
from animora.ml.classic import (
    DecisionNode,
    DecisionTreeModel,
    DecisionTreeVisualizer,
    HardMarginSVMModel,
    KMeansModel,
    KMeansVisualizer,
    LinearRegressionModel,
    LinearRegressionVisualizer,
    LogisticRegressionModel,
    LogisticRegressionVisualizer,
    PCAModel,
    PCAVisualizer,
    SVMVisualizer,
    decision_tree,
    kmeans,
    linear_regression,
    logistic_regression,
    pca,
    svm,
)
from animora.ml.deep_learning import (
    AdamOptimizerModel,
    BackpropagationModel,
    BackpropagationVisualizer,
    BaseOptimizerModel,
    CNNConvolutionModel,
    CNNConvolutionVisualizer,
    MomentumOptimizerModel,
    NeuralNetworkModel,
    NeuralNetworkVisualizer,
    OptimizerVisualizer,
    RNNCellModel,
    RNNVisualizer,
    SGDOptimizerModel,
    adam,
    backpropagation,
    cnn_convolution,
    momentum,
    neural_network_forward,
    rnn_forward,
    sgd,
)
from animora.ml.nlp import (
    AttentionModel,
    AttentionVisualizer,
    EmbeddingModel,
    EmbeddingVisualizer,
    TokenizerModel,
    TokenizerVisualizer,
    TransformerBlockModel,
    TransformerBlockVisualizer,
    attention,
    tokenize,
    transformer_block,
    word_embeddings,
)
from animora.ml.optimization.gradient_descent import (
    GradientDescentModel,
    GradientDescentVisualizer,
    gradient_descent,
)
from animora.ml.surface_plot import SurfacePlot
from animora.ml.tensor_grid import TensorGrid
from animora.ml.vector_field import VectorField

__all__ = [
    "AdamOptimizerModel",
    "AttentionModel",
    "AttentionVisualizer",
    "BackpropagationModel",
    "BackpropagationVisualizer",
    "BaseOptimizerModel",
    "CNNConvolutionModel",
    "CNNConvolutionVisualizer",
    "DecisionNode",
    "DecisionTreeModel",
    "DecisionTreeVisualizer",
    "EmbeddingModel",
    "EmbeddingVisualizer",
    "GradientDescentModel",
    "GradientDescentVisualizer",
    "HardMarginSVMModel",
    "KMeansModel",
    "KMeansVisualizer",
    "LinearRegressionModel",
    "LinearRegressionVisualizer",
    "LogisticRegressionModel",
    "LogisticRegressionVisualizer",
    "MLComponent",
    "MLTrace",
    "MLTraceStep",
    "MomentumOptimizerModel",
    "NeuralNetworkModel",
    "NeuralNetworkVisualizer",
    "OptimizerVisualizer",
    "PCAModel",
    "PCAVisualizer",
    "RNNCellModel",
    "RNNVisualizer",
    "SGDOptimizerModel",
    "SVMVisualizer",
    "SurfacePlot",
    "TensorGrid",
    "TokenizerModel",
    "TokenizerVisualizer",
    "TransformerBlockModel",
    "TransformerBlockVisualizer",
    "VectorField",
    "adam",
    "attention",
    "backpropagation",
    "cnn_convolution",
    "decision_tree",
    "gradient_descent",
    "kmeans",
    "linear_regression",
    "logistic_regression",
    "momentum",
    "neural_network_forward",
    "pca",
    "rnn_forward",
    "sgd",
    "svm",
    "tokenize",
    "transformer_block",
    "word_embeddings",
]
